### DISCUSSION TITLE
Improving DataGrabber `patterns`

### DISCUSSION THREAD

**Discussion by synchon** [juaml/junifer#307] [Ideas]
With the introduction of template space definitions in #252 and #268, the use of `PatternDataladDataGrabber` via YAML is broken as of `9316bca` due to space awareness. The `space` key is added in `get_item` method of the DataGrabber and not defined in the constructor. The `space` key is important for every other component downstream and not having that breaks the pipeline. The solution I propose is not backwards compatible as it re-defines the structure of the `patterns` parameter, but in my opinion the cleanest and leanest way:

### Python:
```python
patterns = {
    "BOLD": "...",
    "T1w": "...",
}
```

### YAML:
```yaml
patterns:
  BOLD: "..."
  T1w: "..."
```

### Python:
```python
patterns = {
    "BOLD": {
        "pattern": "...",
        "space": "...",
    },
    "T1w": {
        "pattern": "...",
        "space": "...",
    },
}
```

### YAML:
```yaml
patterns:
  BOLD:
    pattern: "..."
    space: "..."
  T1w:
    pattern: "..."
    space: "..."
```

I'm happy to discuss alternatives and adapt my solution.

**Comment by LeSasse** [comment]
I think a similar problem exists for when trying to add a pattern for a BOLD_mask. For example I tried to use `PatternDataladDatagrabber` in the YAML to make a AOMIC datagrabber that is not the in-built one, and it didn't work properly, because you need to add this `mask_item` key later on (see: https://github.com/juaml/junifer/blob/9316bca0aa61c3f48946e0c235ea4286d2fd1a87/junifer/datagrabber/aomic/piop1.py#L197)

Maybe something like:

```yaml
patterns:
  BOLD:
    pattern: "..."
    space: "..."
    mask_item: "..."
  T1w:
    pattern: "..."
    space: "..."
    mask_item: "..."
```    
could fix that.
