### ISSUE TITLE
[BUG]: Junifer log files formatting

### ISSUE THREAD

**Issue by LeSasse** [juaml/junifer#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The names of junifer log files put a comma between elements of elements:

![Selection_015](https://user-images.githubusercontent.com/73998642/201862081-d68f2aef-d758-4162-87b9-80671b9c8940.png)

### Expected Behavior

I think something like an underscore might be nicer instead of a comma which is not so nice in a file name.

### Steps To Reproduce

yaml file:

```
workdir: /tmp

datagrabber:
    kind: DataladAOMICPIOP1
    tasks: ["restingstate"]

markers:
  - name: Schaefer100x17_FC
    kind: FunctionalConnectivityParcels
    parcellation: Schaefer100x17
    cor_method: correlation
  - name: Schaefer200x17_FC
    kind: FunctionalConnectivityParcels
    parcellation: Schaefer200x17
    cor_method: correlation
  - name: Schaefer400x17_FC
    kind: FunctionalConnectivityParcels
    parcellation: Schaefer400x17
    cor_method: correlation

preprocess:
    kind: fMRIPrepConfoundRemover
    strategy:
        motion: full
        wm_csf: full
        global_signal: full
    low_pass: 0.08
    high_pass: 0.008

storage: 
  kind: SQLiteFeatureStorage
  uri: /data/project/identification_prediction/data/junifer_aomic/storage/PIOP1

queue:
  jobname: PREPROCESS_PIOP1
  kind: HTCondor
  env:
    kind: conda
    name: junifer
  mem: 8G

```

I just run `junifer queue` on this yaml file.

### Environment

```markdown
junifer:
  version: 0.0.1.dev909
python:
  version: 3.10.6
  implementation: CPython
dependencies:
  click: 8.1.3
  numpy: 1.22.4
  datalad: 0.17.9
  pandas: 1.4.4
  nibabel: 4.0.2
  nilearn: 0.9.2
  sqlalchemy: 1.4.44
  yaml: '6.0'
system:
  platform: Linux-4.19.0-21-amd64-x86_64-with-glibc2.28
environment:
  LC_CTYPE: en_US.UTF-8
  PATH: /home/lsasse/miniconda3/envs/junifer/bin:/home/lsasse/miniconda3/condabin:/home/lsasse/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games
```
```


### Relevant log output

_No response_

### Anything else?

_No response_
